version: '3.7'
services:
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - "4444:4444"
    expose: 
      - 4444
    networks:
      - test
  chrome:
    image: selenium/node-chrome-debug
    container_name: chrome
    deploy:
      replicas: 5
    ports:
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - test
  firefox:
    image: selenium/node-firefox:3.141.59-yttrium
    container_name: firefox
    deploy:
      replicas: 8
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - test

networks:
  test:
    external: false
    name: test


   #instalar node
   #instalar docker
   #instalar docker compose
   #crear archivo docker-compose.yml
   #levantar el servicio

   